spring:
  application:
    name: eureka-server
server:
  port: 6082

eureka:
  instance:
    hostname: master
  client:
    #register-with-eureka: false
    #fetch-registry: false
    serviceUrl:
      defaultZone: http://back:6081/eureka/
